"use client";

import { MouseEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";

type Mode = "explain" | "explore" | "add";

interface GeneratedPage {
  id: string;
  source: string;
  depth: number;
  mode: Mode;
  image: string;
  provider: string;
  model: string;
  textProvider?: string;
  textModel?: string;
  plan?: {
    title: string;
    summary: string;
    nodes: Array<{ title: string; description: string }>;
  };
  prompt: string;
  click: { x: number; y: number } | null;
}

interface GenerationResponse extends GeneratedPage {
  error?: string;
}

const modeLabels: Record<Mode, string> = {
  explain: "Explain",
  explore: "Explore",
  add: "Add"
};

function getInitialSource(searchParams: URLSearchParams) {
  const queryUrl = searchParams.get("url");
  if (queryUrl) {
    return queryUrl;
  }

  const rawQuery = searchParams.toString();
  if (rawQuery.startsWith("http")) {
    return rawQuery;
  }

  return "";
}

export function VisualMapApp() {
  const searchParams = useSearchParams();
  const initialSource = useMemo(() => getInitialSource(searchParams), [searchParams]);
  const [source, setSource] = useState(initialSource);
  const [mode, setMode] = useState<Mode>("explore");
  const [pages, setPages] = useState<GeneratedPage[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState("");
  const hasAutoGenerated = useRef(false);
  const currentPage = pages[pages.length - 1];

  const generatePage = useCallback(
    async (options?: { click?: { x: number; y: number }; nextMode?: Mode }) => {
      const trimmedSource = source.trim();
      if (!trimmedSource) {
        setError("Paste a URL or topic to start.");
        return;
      }

      setIsGenerating(true);
      setError("");

      try {
        const response = await fetch("/api/generate-page", {
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            source: trimmedSource,
            depth: options?.click ? pages.length : 0,
            path: pages.map((page) => `${page.mode}:${page.id}`),
            click: options?.click,
            mode: options?.nextMode ?? mode
          })
        });

        const body = (await response.json()) as GenerationResponse;
        if (!response.ok || body.error) {
          throw new Error(body.error ?? "Generation failed");
        }

        setPages((prev) => [...prev, body]);
      } catch (generationError) {
        setError(
          generationError instanceof Error
            ? generationError.message
            : "Generation failed"
        );
      } finally {
        setIsGenerating(false);
      }
    },
    [mode, pages, source]
  );

  useEffect(() => {
    if (!initialSource || hasAutoGenerated.current) {
      return;
    }

    hasAutoGenerated.current = true;
    setSource(initialSource);
    void generatePage();
  }, [generatePage, initialSource]);

  function handleCanvasClick(event: MouseEvent<HTMLDivElement>) {
    if (!currentPage || isGenerating) {
      return;
    }

    const rect = event.currentTarget.getBoundingClientRect();
    const x = (event.clientX - rect.left) / rect.width;
    const y = (event.clientY - rect.top) / rect.height;
    void generatePage({ click: { x, y } });
  }

  function handleBack() {
    setPages((prev) => prev.slice(0, -1));
  }

  function handleModeChange(nextMode: Mode) {
    setMode(nextMode);
  }

  return (
    <main className="visual-shell">
      <section className="canvas-stage" onClick={handleCanvasClick}>
        {currentPage ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            className="generated-image"
            src={currentPage.image}
            alt="Generated VisualMap canvas"
          />
        ) : (
          <div className="empty-canvas">
            <div className="empty-orbit empty-orbit-a" />
            <div className="empty-orbit empty-orbit-b" />
            <div className="empty-title">VisualMap</div>
          </div>
        )}

        {isGenerating ? (
          <div className="generation-veil">
            <div className="pulse-ring" />
            <span>Rendering visual map</span>
          </div>
        ) : null}
      </section>

      <div className="top-controls" onClick={(event) => event.stopPropagation()}>
        <div className="mode-switch" aria-label="Mode switch">
          {(Object.keys(modeLabels) as Mode[]).map((item) => (
            <button
              className={item === mode ? "mode-button active" : "mode-button"}
              key={item}
              onClick={() => handleModeChange(item)}
              type="button"
            >
              {modeLabels[item]}
            </button>
          ))}
        </div>

        <button
          className="icon-button"
          disabled={!pages.length || isGenerating}
          onClick={handleBack}
          title="Back"
          type="button"
        >
          ←
        </button>
      </div>

      <div className="source-command" onClick={(event) => event.stopPropagation()}>
        <input
          aria-label="Source URL or topic"
          onChange={(event) => setSource(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Enter") {
              void generatePage();
            }
          }}
          placeholder="Paste a URL or type a topic"
          value={source}
        />
        <button disabled={isGenerating} onClick={() => void generatePage()} type="button">
          Generate
        </button>
      </div>

      <aside className="status-panel" onClick={(event) => event.stopPropagation()}>
        <div>
          <span className="eyebrow">Phase 1</span>
          <strong>Flipbook-style direct generation</strong>
        </div>
        <p>
          Full-screen image canvas, click-to-drill navigation, provider-isolated image
          generation.
        </p>
        {currentPage ? (
          <dl>
            <div>
              <dt>Depth</dt>
              <dd>{currentPage.depth}</dd>
            </div>
            <div>
              <dt>Provider</dt>
              <dd>{currentPage.provider}</dd>
            </div>
            <div>
              <dt>Model</dt>
              <dd>{currentPage.model}</dd>
            </div>
            <div>
              <dt>Planner</dt>
              <dd>{currentPage.textProvider ?? "unknown"}</dd>
            </div>
          </dl>
        ) : null}
        {currentPage?.plan ? (
          <div className="plan-preview">
            <strong>{currentPage.plan.title}</strong>
            <p>{currentPage.plan.summary}</p>
          </div>
        ) : null}
        {error ? <p className="error-text">{error}</p> : null}
      </aside>
    </main>
  );
}
